Fix declaration of `get_miniscope_root_data_dir`
datajoint/element-miniscope pull request #54
Opened 2024-01-17 01:03 UTC by MilagrosMarin

2024-01-17 12:00 UTC, kushalbakshi requested changes
Looks good! Please update the version and CHANGELOG.

2024-01-18 11:38 UTC, MilagrosMarin commented
These modifications don't require a version update.

2024-01-18 12:01 UTC, kushalbakshi commented
> These modifications don't require a version update.

Is not a [patch release](https://www.baeldung.com/cs/semantic-versioning)?

2024-01-18 12:07 UTC, MilagrosMarin commented
> > These modifications don't require a version update.
> 
> 
> 
> Is not a [patch release](https://www.baeldung.com/cs/semantic-versioning)?

Based on internal agreement, there is no requirement to release a new version for these changes.

2024-01-18 12:13 UTC, kushalbakshi commented
> > > These modifications don't require a version update.
> > 
> > 
> > Is not a [patch release](https://www.baeldung.com/cs/semantic-versioning)?
> 
> Based on internal agreement, there is no requirement to release a new version for these changes.

I haven't agreed to that. In the future please do one of the following: 

- update the version on any PR to be merged to the main branch - **THIS IS SOP**.
- Explain why we're deviating from standard procedures in the PR description.
- Only request reviews from reviewers with whom you've previously agreed to deviate from standard procedures to wrap up the PR as quickly as possible

2024-01-22 18:05 UTC, MilagrosMarin commented
> > > > These modifications don't require a version update.
> > > 
> > > 
> > > Is not a [patch release](https://www.baeldung.com/cs/semantic-versioning)?
> > 
> > 
> > Based on internal agreement, there is no requirement to release a new version for these changes.
> 
> I haven't agreed to that. In the future please do one of the following:
> 
> * update the version on any PR to be merged to the main branch - **THIS IS SOP**.
> * Explain why we're deviating from standard procedures in the PR description.
> * Only request reviews from reviewers with whom you've previously agreed to deviate from standard procedures to wrap up the PR as quickly as possible


Thank you for underscoring the importance of maintaining clear practices for our open-source repositories. Here's a concise update on the ongoing discussion:

Initially, following guidance from our Slack channel, we determined that a version bump isn't necessary after a PR review in notebooks, README, and tutorial_pipeline.py. 

However, this PR conversation has sparked an ongoing discussion on best practices for versioning and changelog management, with forthcoming documentation from @Kushal. Additionally, we are exploring the adoption of the conventional commit vscode extension.

Given that this discussion is still pending resolution, I plan to manually bump the CHANGELOG and version following Kushal's guidance, and will include these details in the PR description. We remain open to considering alternative methods, such as the potential auto-generation of the CHANGELOG using VSCode extensions.

2024-01-22 18:22 UTC, kushalbakshi approved these changes
Thank you @MilagrosMarin!

2024-01-22 18:22 UTC, merged